.MODEL small
.CODE
INICIO:
MOV AX, @DATA
MOV DS, AX
MOV DX, OFFSET TEXTO
MOV AH,9
INT 21H
MOV DX, OFFSET TEXTO1
MOV AH,9
INT 21H
MOV DX, OFFSET TEXTO2
MOV AH,9
INT 21H
INT 21H
.DATA
TEXTO DB '?HOW ARE YOY?', 13,10, ' $'
TEXTO1 DB 'WELCOME TO ASSAMBLY', 13, 10, '$'
TEXTO2 DB 'Low-level language', 13,10, '$'
.STACK
DB 64 DUP ('PILA')
END INICIO